language: node_js
node_js:
  - 0.12
  - 4
  - 5

sudo: false
git:
  depth: 1000000

before_script:
  - npm install -g nodegit

script:
  - npm run ci

notifications:
  email:
  - kimmobrunfeldt+git-hours@gmail.com

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
